### ISSUE TITLE
Unit tests for Agrona are failing on Java 8 on 32bit architecture

### ISSUE THREAD

**Issue by alingherasim** [real-logic/Agrona#9]
**Description:**
Some unit tests in Agrona are failing on a 32bit architecture due to the fact that the memory alignment on a 32bit architecture is 4 bytes instead 8 bytes which is the case for a 64bit architecture.

**Environment:** 
Java 8 on 32bit architecture

**Steps to reproduce:**
Try to perform a build of Agrona using Gradle.

**Logs:**
This is the output generated by the unit tests:

```
uk.co.real_logic.agrona.concurrent.AtomicBufferTest > shouldVerifyBufferAlignment FAILED
    org.junit.experimental.theories.internal.ParameterizedAssertionError
        Caused by: java.lang.AssertionError at AtomicBufferTest.java:86

uk.co.real_logic.agrona.concurrent.CountersManagerTest > managerShouldNotOverAllocateCounters FAILED
    java.lang.IllegalStateException at CountersManagerTest.java:40

uk.co.real_logic.agrona.concurrent.CountersManagerTest > allocatedCountersCanBeMapped FAILED
    java.lang.IllegalStateException at CountersManagerTest.java:40

uk.co.real_logic.agrona.concurrent.CountersManagerTest > managerShouldStoreLabels FAILED
    java.lang.IllegalStateException at CountersManagerTest.java:40

uk.co.real_logic.agrona.concurrent.CountersManagerTest > managerShouldStoreMultipleLabels FAILED
    java.lang.IllegalStateException at CountersManagerTest.java:40

uk.co.real_logic.agrona.concurrent.CountersManagerTest > shouldFreeAndReuseCounters FAILED
    java.lang.IllegalStateException at CountersManagerTest.java:40
```

This is the stack trace for a failing test:

```
	org.junit.experimental.theories.internal.ParameterizedAssertionError: shouldVerifyBufferAlignment("uk.co.real_logic.agrona.concurrent.UnsafeBuffer@1833882" <from BYTE_ARRAY_BACKED>)
	at org.junit.experimental.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:288)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:237)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:218)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:204)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:212)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:202)
	at org.junit.experimental.theories.Theories$TheoryAnchor.evaluate(Theories.java:187)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.AssertionError: All buffers should be aligned java.lang.IllegalStateException: AtomicBuffer is not correctly aligned: addressOffset=12 in not divisible by 8
	at org.junit.Assert.fail(Assert.java:88)
	at uk.co.real_logic.agrona.concurrent.AtomicBufferTest.shouldVerifyBufferAlignment(AtomicBufferTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.experimental.theories.Theories$TheoryAnchor$2.evaluate(Theories.java:274)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:232)
	... 20 more
```

**Note:**
To retrieve the JVM architecture we can use the following method call: System.getProperty("sun.arch.data.model"); to retrieve that system property. (http://docs.oracle.com/javame/config/cdc/cdc-opt-impl/ojmeec/1.1/architecture/html/properties.htm)

**Comment by alingherasim** [comment]
Tested the issue using JDK 1.8.0.45 and the build works fine.
